name: trips-CI
on:
  pull_request:
    branches: [main, ch3]
    paths:
      - apis/trips/**
      - .github/workflows/trips-CI.yml

  push:
    branches: [main, ch3]
    paths:
      - apis/trips/**
      - .github/workflows/trips-CI.yml


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v .
        
      - name: where am I
        run: ls

      - name: Test
        run: go test ./tripgo -run Unit
