name: user-java-CI
on:
  pull_request:
    branches: [main, ch3]
    paths:
      - apis/user-java/**
      - .github/workflows/user-java-CI.yml

  push:
    branches: [main, ch3]
    paths:
      - apis/user-java/**
      - .github/workflows/user-java-CI.yml

defaults:
  run:
    working-directory: apis/user-java/

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: nashmaniac/create-issue-action@v1.1
        if: failure()
        name: Create Issue Action
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: |
            ${{ github.workflow }} Workflow failed for commit ${{github.sha}}
            Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
